[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "^0.2"
wasm-bindgen-futures = "^0.4"
js-sys = "^0.3"
serde = { version ="^1.0", features = ["derive"] }
rmp-serde = "^1.1"
m3u8-rs = "^5.0"

libp2p = {version = "^0.52", features = ["full"]}
# Remove when Rust supports async traits
async-trait = "^0.1"
# I don't like it
either = "^1.9.0"
async-std = "^1.12"
lru = "0.11.0"
void = "^1.0"

[dependencies.web-sys]
version = "^0.3"
features = [
    "Window",
    "console",
    "MessageEvent",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "RtcPeerConnection",
    "RtcSignalingState",
    "RtcSdpType",
    "RtcSessionDescriptionInit",
    "RtcPeerConnectionIceEvent",
    "RtcIceCandidate",
    "RtcDataChannel",
    "RtcDataChannelEvent",
    "WebSocket",
    "BinaryType",
    "Blob",
    "ErrorEvent",
    "FileReader",
    "MessageEvent",
    "ProgressEvent",
    "WebSocket",
]
