[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "^0.2"
wasm-bindgen-futures = "^0.4"
js-sys = "^0.3"
serde = { version ="^1.0", features = ["derive"] }
rmp-serde = "^1.1"
libp2p = {version = "^0.51", features = ["full"]}
# Remove me when not needed
rand = "^0.8"
# Remove when Rust supports async traits
async-trait = "^0.1"
# I don't like it
either = "1.8.1"
# I don't like it either
futures = "0.3.26"
async-std = "^1.12"

[dependencies.web-sys]
version = "^0.3"
features = [
    "Window",
    "console",
    "MessageEvent",
    "RtcPeerConnection",
    "RtcSignalingState",
    "RtcSdpType",
    "RtcSessionDescriptionInit",
    "RtcPeerConnectionIceEvent",
    "RtcIceCandidate",
    "RtcDataChannel",
    "RtcDataChannelEvent",
    "WebSocket",
    "BinaryType",
    "Blob",
    "ErrorEvent",
    "FileReader",
    "MessageEvent",
    "ProgressEvent",
    "WebSocket",
]
