contact_links:
    - name: 🤔 Questions and Help
      url: https://github.com/ferrohd/pida/discussions
      about: This issue tracker is not for support questions. Please refer to the GitHub Discussion section.
