[package]
name = "marecchia-core"
description = "WASM module for the Marecchia project"
version = "0.0.6"
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "^0.1.80"
console_error_panic_hook = "0.1.7"
libp2p = { version = "^0.53.2", features = [
    "wasm-bindgen",
    "gossipsub",
    "ping",
    "identify",
    "autonat",
    "noise",
    "memory-connection-limits",
    "secp256k1",
    "rendezvous",
    "rsa",
    "metrics",
    "ecdsa",
    "macros",
    "ed25519"
] }
libp2p-webrtc-websys = "0.3.0-alpha"
libp2p-webtransport-websys = "0.2.0"
wasm-bindgen = "^0.2.92"
wasm-bindgen-futures = "^0.4.42"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
js-sys = "^0.3.69"
tracing = "0.1.40"
tracing-subscriber = "0.3"
tracing-web = "0.1.3"
