[package]
name = "marecchia-core"
description = "WASM module for the Marecchia project"
version = "0.0.6"
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "^0.1.80"
console_error_panic_hook = "0.1.7"
libp2p = { version = "^0.53.2", features = ["full"] }
libp2p-webrtc-websys = "0.3.0-alpha"

wasm-bindgen = "^0.2.92"
wasm-bindgen-futures = "^0.4.42"
futures = { version = "0.3.30", default-features = false, features = ["alloc"] }
js-sys = "^0.3.69"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-web = "0.1.3"
