name: CI

on:
  push:
    branches: [master]
    paths:
      - 'crates/**'
      - 'marecchia/**'
  pull_request:
    branches: [master]
    paths:
      - 'crates/**'
      - 'marecchia/**'

env:
  CARGO_TERM_COLOR: always

jobs:
    rs-toolchain:
        name: ⚒️ Toolchain
        runs-on: ubuntu-latest
        steps:
          - name: ⚒️ Toolchain Info
            run: |
              cargo --version --verbose
              rustc --version
              cargo clippy --version

    rs-clippy:
        name: 📎 Clippy
        needs: rs-toolchain
        runs-on: ubuntu-latest
        steps:
            - name: 🛒 Checkout
              uses: actions/checkout@v6

            - name: ⚡ Cache
              uses: actions/cache@v5
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target
                key: ${{ runner.os }}-cargo-${{ hashFiles('crates/Cargo.lock') }}

            #- name: 📎 Clippy
            #  working-directory: crates
            #  run: |
            #    cargo rs-clippy --

    rs-test:
        name: 🧪 Test
        needs: rs-toolchain
        runs-on: ubuntu-latest
        steps:
            - name: 🛒 Checkout
              uses: actions/checkout@v6

            - name: ⚡ Cache
              uses: actions/cache@v5
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target
                key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

            #- name: 🧪 Test
            #  working-directory: crates
            #  run: |
            #    cargo rs-test --all

    rs-build-marecchia-core:
        name: 🔨 Build @marecchia/marecchia-core
        needs: rs-toolchain
        runs-on: ubuntu-latest
        steps:
            - name: 🛒 Checkout
              uses: actions/checkout@v6

            - name: ⚡ Cache
              uses: actions/cache@v5
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target
                key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

            - name: 🪛 Setup Node.js
              uses: actions/setup-node@v6
              with:
                node-version: '24'

            - name: 📦 Install wasm-pack
              working-directory: crates
              run: npm install -g wasm-pack

            - name: 🎯 Install WASM Target
              working-directory: crates
              run: rustup target add wasm32-unknown-unknown

            - name: 🔨 Build
              working-directory: crates/marecchia-core
              run: wasm-pack build --target web --scope marecchia

            - name: 💾 Save Artifact
              uses: actions/upload-artifact@v7
              with:
                name: marecchia-core
                path: ./crates/marecchia-core/pkg

    ts-build:
        name: 🛠️ Build Typescript
        runs-on: ubuntu-latest
        needs: rs-build-marecchia-core
        strategy:
          fail-fast: false
          matrix:
            packages:
              - name: '@marecchia/hlsjs'
                path: hlsjs

        steps:
            - name: 🛒 Checkout
              uses: actions/checkout@v6

            - name: 🪛 Setup Node.js
              uses: actions/setup-node@v6
              with:
                node-version: '24'

            - name: Get @marecchia/marecchia-core
              uses: actions/download-artifact@v8
              with:
                name: marecchia-core
                path: ./crates/marecchia-core/pkg

            - name: 🗑️ Delete Artifact
              uses: geekyeggo/delete-artifact@v6
              with:
                  name: marecchia-core

            - name: 📦 Install Dependencies
              working-directory: marecchia
              run: npm install

            - name: 🛠️ Build ${{ matrix.packages.name }}
              working-directory: marecchia/packages/${{ matrix.packages.path }}
              run: npm run build

    rs-build-marecchia-tracker:
        name: 🔨 Build Marecchia Tracker
        needs: rs-toolchain
        runs-on: ubuntu-latest
        steps:
            - name: 🛒 Checkout
              uses: actions/checkout@v6

            - name: ⚡ Cache
              uses: actions/cache@v5
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target
                key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

            - name: 🔨 Build
              working-directory: crates/marecchia-tracker
              run: cargo build
